### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by IrakozeLoraine**

### CODE REVIEW

**Comment by claranceliberi** [comment]
Hello loraine, it seems like you have some conflicts, look at them and we merge

**Comment by IrakozeLoraine** [comment]
> Hello loraine, it seems like you have some conflicts, look at them and we merge

Hello claranceliberi, please check again and approve or let me know

**Comment by claranceliberi** [comment]
> > Hello Loraine, it seems like you have some conflicts, look at them and we merge
> 
> Hello claranceliberi, please check again and approve or let me know

Everything is now set

**Comment by claranceliberi** [comment]
@IrakozeLoraine  take a look we have integrated tailwind, if you feel like you want to use it you can use check it out

**Pull request merged**
