### PR TITLE
Svg rework

### PR DESCRIPTION
**Pull request by claranceliberi**
Once everything detailed below is done check this
- [ ] SVG problem
- [ ] Welcome, Register and Login screen re-arrangement

### CODE REVIEW

**Comment by claranceliberi** [comment]
@IrakozeLoraine  Take a look at the SVG you imported in this app, I don't know why you imported them as react-native component 
```js
// importing it this way
 import Logo from '../assets/images/colored-logo.svg';

// and using it this way
<Logo width="200" height="100" style={tw`self-center`} />
```


we don't know how you configured it but it is not working on my side and @IkireziDivine01 , so if there is a way you can let us know how to overcome this or find another way to do this

In the meantime I have commented it

**Comment by claranceliberi** [comment]
And also @IrakozeLoraine  the first screen page is stacking, it is just being displayed and we can't go to the next page, so if there is any workaround you can helps us

**Comment by claranceliberi** [comment]
@IrakozeLoraine  remember to re-arrange  the login and signup pages and even welcome  page , they don't have to appear on the button navigation bar,

**Comment by IrakozeLoraine** [comment]
> @IrakozeLoraine remember to re-arrange the login and signup pages and even welcome page , they don't have to appear on the button navigation bar,

Done

**Pull request merged**
